apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: accounts
  name: accounts
spec:
  replicas: 3
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
        - name: accounts
          image: IMAGE_NAME_HERE
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URI
              value: postgresql://userUVB:VmrPvFuk1phjR3pa@postgresql:5432/sampledb
